apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-arc-app
  namespace: hello-arc-test
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: hello-arc-test-app-release
  chart:
    spec:
      chart: ./charts/hello-arc-app
  values:
    image:
      repository: azurearcjumpstart.azurecr.io/hello-arc-gitops
      tag: latest
    replicaCount: 3
    env:
      name: MESSAGE
      value: Welcome Jorge Perona to Azure Arc GitOps Demo - Monday 29th - cluster2!
