apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-arc-app
  namespace: hello-arc-test
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: hello-arc-test-app-release
  chart:
    spec:
      chart: ./charts/hello-arc-app
  values:
    image:
      repository: liorkamrat/hello-arc
      tag: latest
    replicaCount: 1
    env:
      name: MESSAGE
      value: Gracias Ciencia Terapia por vuestra labor!!
